# Name of your application. Used to uniquely configure containers.
service: pp
image: evgev/cp

servers:
  - 185.22.60.126
registry:
  username: evgev
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  clear:
    DATABASE_URL: postgres://postgres@185.22.60.126/price_comparison_production
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    REDIS_URL: redis://185.22.60.126:6379/0

  secret:
    - RAILS_MASTER_KEY

builder:
  multiarch: false
  args:
    RUBY_VERSION: 3.1.0

accessories:
  redis:
    image: redis:6.2.12-alpine
    hosts:
      - 185.22.60.126
    volumes:
      - redis:/data
    port: 6379


  postgres:
    image: postgres:14.9-alpine
    hosts:
      - 185.22.60.126
    port: 5432
    volumes:
      - postgres:/var/lib/postgresql/data:cached
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: E7%qekU305Yg!